### ISSUE TITLE
Support discussions

### ISSUE THREAD

**Issue by Hacksore** [Norfeldt/github-issue-reactions-browser-extension#17]
Seems discussions don't work and you get an infinite loading state 😅.

ex: https://github.com/facebook/create-react-app/discussions/11767

**Comment by Norfeldt** [comment]
@Hacksore it was broken, but I have fixed it now - also made some improvements so you can see which ones you have upvoted. 🙂

It's for review on Chrome and Firefox extension stores now.

**Comment by Hacksore** [comment]
Awesome if you drop a comment here when they go live I can test the chrome version.

**Comment by Norfeldt** [comment]
It should be live now 🤘
