### ISSUE TITLE
Error: ENOENT: no such file or directory, open manifest.json

### ISSUE THREAD

**Issue by tanyeun** [Norfeldt/github-issue-reactions-browser-extension#18]
On windows 10

node version v18.14.0
yarn version 1.22.19

![image](https://user-images.githubusercontent.com/22489112/217116272-62a6bb51-5f06-4cd7-9148-836ac583505e.png)

On windows 10 WSL2 Ubuntu 22.04

node version v18.12.1
yarn version 1.22.19

![image](https://user-images.githubusercontent.com/22489112/217116405-8a4526d0-6322-4418-b6b1-f29f3d335fb5.png)

**Comment by Norfeldt** [comment]
I think it might be related to this https://stackoverflow.com/questions/34811222/writefile-no-such-file-or-directory

so perhaps it would help if you just make some empty folders `dist/chrome` and `dist/firefox` and try to run `yarn bundle`

<img width="319" alt="Screenshot 2023-02-14 at 21 25 16" src="https://user-images.githubusercontent.com/678806/218853956-3e1b71bf-12ef-45fa-b4c3-516c008b2819.png">

**Comment by Norfeldt** [comment]
That is now fixed 👍
