### ISSUE TITLE
Page reload UI jitter

### ISSUE THREAD

**Issue by Hacksore** [Norfeldt/github-issue-reactions-browser-extension#21]
This is what I see now when refreshing the page when using the compact/inline mode.

Would it be possible to wait until everything is loaded/computed before rendering the items?

https://user-images.githubusercontent.com/996134/219873173-304f2836-ab76-493a-b219-30164e5b7038.mp4

**Comment by Hacksore** [comment]
Seems there is jitter too when reacting to something as well.

https://user-images.githubusercontent.com/996134/221369237-86db2cb8-8391-49c0-ac84-f295f6d59fd4.mp4

**Comment by Norfeldt** [comment]
It's my plan to refactor it to use react - that should fix this issue. I just need to find the time to do it.

**Comment by Hacksore** [comment]
I think this is a known issue for now.

Let's hope a refactor to react solves this jitter issues 🙏.
