### ISSUE TITLE
Bug: No Reactions Found

### ISSUE THREAD

**Issue by pcbowers** [Norfeldt/github-issue-reactions-browser-extension#27]
I can't seem to get this extension to work successfully. I am running it in Chrome Version 111.0.5563.64 (Official Build) (64-bit) with v2.4.2 of the Extension (I am using Ubuntu 22.04, though I'm unsure whether this impacts extension viability). I enabled logs for the extension and am getting the following warning:

```
Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```

I am not sure if this is what is causing the issue, but thought I would include it!

Here is a screenshot demonstrating the lack of reactions, even though reactions should be showing:

![image](https://user-images.githubusercontent.com/41601975/226681026-7c38ffb1-26c2-47f9-a987-d7e6e0249382.png)

Thanks again for your work on this project!

**Comment by Norfeldt** [comment]
this might be something to do with different emojis on Linux 🤔💭

I don't have a Linux machine right now, so would you mind try to appending the linux emojis (copy paste) to this array:

https://github.com/Norfeldt/github-issue-reactions-browser-extension/blob/main/src/index.ts#L189

> const reactions = ['👍', '🚀', '🎉', '😄', '❤️', '😕', '👎', '👀']

then you should be able to see if it works by following this guide on how-to run it locally:

https://github.com/Norfeldt/github-issue-reactions-browser-extension/blob/main/README.md?plain=1#:~:text=%23%23%20Manual%20Setup,7.%20Enjoy!%20%F0%9F%91%8D

**Comment by pcbowers** [comment]
@Norfeldt That didn't seem to fix it. Here's the HTML that I see for the reaction on my initial issue:

```html
<div class="js-comment-reactions-options d-flex flex-items-center flex-row flex-wrap">
  <button
    name="input[content]"
    id="reactions--reaction_button_component-0a5963"
    value="EYES react"
    data-button-index-position="7"
    data-reaction-label="Eyes"
    data-reaction-content="eyes"
    aria-pressed="false"
    aria-label="react with eyes"
    type="submit"
    data-view-component="true"
    class="social-reaction-summary-item js-reaction-group-button js-optimistic-reaction-render-button btn-link d-flex no-underline color-fg-muted flex-items-baseline mr-2"
    aria-describedby="tooltip-5b6218e3-da21-4c8e-87e4-2d26274af0ae">
    <g-emoji
      alias="eyes"
      fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f440.png"
      class="social-button-emoji"
      ><img
        class="emoji"
        alt="eyes"
        height="20"
        width="20"
        src="https://github.githubassets.com/images/icons/emoji/unicode/1f440.png"
    /></g-emoji>
    <span class="js-discussion-reaction-group-count">1</span>
  </button>
  <tool-tip
    id="tooltip-5b6218e3-da21-4c8e-87e4-2d26274af0ae"
    for="reactions--reaction_button_component-0a5963"
    data-direction="n"
    data-type="description"
    data-view-component="true"
    class="position-absolute sr-only"
    role="tooltip"
    style="left: -23.1406px; top: 829.625px"
    >Hacksore reacted with eyes emoji</tool-tip
  >
  <div class="js-reactions-container">
    <details
      class="dropdown details-reset details-overlay d-inline-block js-all-reactions-popover"
      hidden="">
      <summary
        aria-haspopup="true"
        data-view-component="true"
        class="Button--link Button--medium Button">
        <span class="Button-content">
          <span class="Button-label">All reactions</span>
        </span>
      </summary>

      <ul class="dropdown-menu dropdown-menu-se">
        <li class="dropdown-item" aria-label="Hacksore reacted with eyes emoji">
          <g-emoji
            alias="eyes"
            fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f440.png"
            class="social-button-emoji mr-2"
            ><img
              class="emoji"
              alt="eyes"
              height="20"
              width="20"
              src="https://github.githubassets.com/images/icons/emoji/unicode/1f440.png"
          /></g-emoji>
          <span>1 reaction</span>
        </li>
      </ul>
    </details>
  </div>
</div>
```

It looks like it doesn't use emojis but an image instead. I tried on my Windows 11 machine and the same thing happened (`no reactions found`). I'm not sure if maybe I just have a weird setting on my github toggled, or if only Mac's use emojis? I'm not sure. There seems like several ways that one could select for the emoji though, but by using either `[data-reaction-content="eyes"]` or `g-emoji[alias="eyes"]`

**Comment by Norfeldt** [comment]
Thank you @pcbowers - I wish you a nice week 🤗
